"""
Pydantic request and response schemas for the Production AI Platform API.

Responsibilities:
- Validate incoming client requests.
- Define consistent API response models.
- Provide automatic OpenAPI documentation.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ChatRequest(BaseModel):
    """
    Request payload for the chat endpoint.
    """

    question: str = Field(
        ...,
        min_length=1,
        max_length=4000,
        description="The user's question.",
        examples=["Explain Python decorators."],
    )

    session_id: str | None = Field(
        default=None,
        description="Optional conversation/session identifier.",
        examples=["user-123"],
    )

    use_cache: bool = Field(
        default=True,
        description="Whether cached responses may be used.",
    )


class Source(BaseModel):
    """
    Information about a retrieved source document.
    """

    document: str = Field(
        ...,
        description="Document filename or identifier.",
    )

    score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Normalized retrieval score.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional document metadata.",
    )


class ChatResponse(BaseModel):
    """
    Response returned from the chat endpoint.
    """

    answer: str = Field(
        ...,
        description="Final answer generated by the LLM.",
    )

    sources: list[Source] = Field(
        default_factory=list,
        description="Retrieved supporting sources.",
    )

    cached: bool = Field(
        default=False,
        description="True if the answer came from the response cache.",
    )

    grounded: bool = Field(
        default=True,
        description="Whether the answer passed groundedness validation.",
    )

    latency_ms: float = Field(
        ...,
        ge=0,
        description="End-to-end processing time in milliseconds.",
    )

    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "example": {
                "answer": "A decorator is a callable that wraps another function.",
                "sources": [
                    {
                        "document": "python_decorators.md",
                        "score": 0.97,
                        "metadata": {
                            "page": 1,
                            "source": "docs",
                        },
                    }
                ],
                "cached": False,
                "grounded": True,
                "latency_ms": 842.6,
            }
        },
    )


class HealthResponse(BaseModel):
    """
    Health check response.
    """

    status: str = Field(
        ...,
        examples=["healthy"],
    )

    version: str = Field(
        ...,
        examples=["1.0.0"],
    )


class ErrorResponse(BaseModel):
    """
    Standard API error response.
    """

    detail: str = Field(
        ...,
        description="Human-readable error message.",
    )
